using DurableAgent.Core.Models;

namespace DurableAgent.Functions.Models;

/// <summary>
/// HTTP request body for submitting feedback via the API.
/// <see cref="FeedbackId"/> and <see cref="SubmittedAt"/> are optional;
/// the API generates defaults when they are absent.
/// </summary>
public sealed record FeedbackSubmissionRequest
{
    /// <summary>Optional feedback ID. Generated by the server when omitted or blank.</summary>
    public string? FeedbackId { get; init; }

    /// <summary>Optional submission timestamp. Defaults to <see cref="DateTimeOffset.UtcNow"/>.</summary>
    public DateTimeOffset? SubmittedAt { get; init; }

    /// <summary>Identifier of the store where the feedback originated.</summary>
    public string? StoreId { get; init; }

    /// <summary>Identifier of the associated order.</summary>
    public string? OrderId { get; init; }

    /// <summary>Customer details associated with the feedback.</summary>
    public CustomerInfo? Customer { get; init; }

    /// <summary>Channel through which the feedback was submitted (e.g., "kiosk", "web", "app").</summary>
    public string? Channel { get; init; }

    /// <summary>Customer rating (1–5).</summary>
    public int? Rating { get; init; }

    /// <summary>Free-text feedback comment.</summary>
    public string? Comment { get; init; }

    /// <summary>Identifier of the flavor the customer tried (optional).</summary>
    public string? FlavorId { get; init; }

    /// <summary>
    /// Validates the request and returns a list of validation errors (empty when valid).
    /// </summary>
    public IReadOnlyList<string> Validate()
    {
        var errors = new List<string>();

        if (string.IsNullOrWhiteSpace(StoreId))
            errors.Add("storeId is required.");
        if (string.IsNullOrWhiteSpace(OrderId))
            errors.Add("orderId is required.");
        if (Customer is null)
            errors.Add("customer is required.");
        else
        {
            if (string.IsNullOrWhiteSpace(Customer.PreferredName))
                errors.Add("customer.preferredName is required.");
            if (string.IsNullOrWhiteSpace(Customer.FirstName))
                errors.Add("customer.firstName is required.");
            if (string.IsNullOrWhiteSpace(Customer.LastName))
                errors.Add("customer.lastName is required.");
            if (string.IsNullOrWhiteSpace(Customer.Email))
                errors.Add("customer.email is required.");
            if (string.IsNullOrWhiteSpace(Customer.PhoneNumber))
                errors.Add("customer.phoneNumber is required.");
        }
        if (string.IsNullOrWhiteSpace(Channel))
            errors.Add("channel is required.");
        if (Rating is null)
            errors.Add("rating is required.");
        else if (Rating is < 1 or > 5)
            errors.Add("rating must be between 1 and 5.");
        if (string.IsNullOrWhiteSpace(Comment))
            errors.Add("comment is required.");

        return errors;
    }

    /// <summary>
    /// Maps this request to a <see cref="FeedbackMessage"/>, generating
    /// <see cref="FeedbackId"/> and <see cref="SubmittedAt"/> when absent.
    /// Call <see cref="Validate"/> first to ensure required fields are present.
    /// </summary>
    public FeedbackMessage ToFeedbackMessage() => new()
    {
        FeedbackId = string.IsNullOrWhiteSpace(FeedbackId) ? Guid.NewGuid().ToString() : FeedbackId,
        SubmittedAt = SubmittedAt ?? DateTimeOffset.UtcNow,
        StoreId = StoreId!,
        OrderId = OrderId!,
        Customer = Customer!,
        Channel = Channel!,
        Rating = Rating!.Value,
        Comment = Comment!,
        FlavorId = FlavorId,
    };
}
