namespace DurableAgent.Functions.Models;

/// <summary>
/// HTTP request body for submitting an order via the API.
/// </summary>
public sealed record OrderRequest
{
    public string? FlavorId { get; init; }
    public string? FirstName { get; init; }
    public string? LastName { get; init; }
    public string? StreetAddress { get; init; }
    public string? AddressLine2 { get; init; }
    public string? City { get; init; }
    public string? State { get; init; }
    public string? ZipCode { get; init; }
    public string? Email { get; init; }
    public string? PhoneNumber { get; init; }

    /// <summary>Order reference generated by the web app (e.g., "FRY-20260308-AB12").</summary>
    public string? OrderReference { get; init; }
}
