namespace DurableAgent.Functions.Models;

/// <summary>
/// HTTP request body for submitting an order via the API.
/// </summary>
public sealed record OrderRequest
{
    public string? FlavorId { get; init; }
    public string? FirstName { get; init; }
    public string? LastName { get; init; }
    public string? StreetAddress { get; init; }
    public string? AddressLine2 { get; init; }
    public string? City { get; init; }
    public string? State { get; init; }
    public string? ZipCode { get; init; }
    public string? Email { get; init; }
    public string? PhoneNumber { get; init; }

    /// <summary>Number of 1-gallon units ordered (1–10).</summary>
    public int? Quantity { get; init; }

    /// <summary>Order reference generated by the web app (e.g., "FRY-20260308-AB12").</summary>
    public string? OrderReference { get; init; }

    /// <summary>
    /// Validates the request and returns a list of validation errors (empty when valid).
    /// </summary>
    public IReadOnlyList<string> Validate()
    {
        var errors = new List<string>();

        if (string.IsNullOrWhiteSpace(OrderReference))
            errors.Add("orderReference is required.");
        if (string.IsNullOrWhiteSpace(FlavorId))
            errors.Add("flavorId is required.");
        if (Quantity is null or < 1 or > 10)
            errors.Add("quantity must be between 1 and 10.");
        if (string.IsNullOrWhiteSpace(FirstName))
            errors.Add("firstName is required.");
        if (string.IsNullOrWhiteSpace(LastName))
            errors.Add("lastName is required.");
        if (string.IsNullOrWhiteSpace(StreetAddress))
            errors.Add("streetAddress is required.");
        if (string.IsNullOrWhiteSpace(City))
            errors.Add("city is required.");
        if (string.IsNullOrWhiteSpace(State))
            errors.Add("state is required.");
        if (string.IsNullOrWhiteSpace(ZipCode))
            errors.Add("zipCode is required.");

        return errors;
    }
}
